In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../datasets/HousePricePrediction.csv")

In [3]:
print(df.info())
print(df.describe())
print(df.isna())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB
None
                Id   MSSubClass        LotArea  OverallCond    YearBuilt  \
count  2919.000000  2919.000000    2919.000000  2919.000000  2919.000000
mean   1459.000000    57.137718   10168.114080     5.564577  1971.312778
std     842.787043    42.517628    7886.996359     1.113131    30.291442
min       0.000000    20.000000    1300.000000     1.000000  1872.000000
25%     729.500000    20.000000    7478.000000     5.000000  1953.500000
50%    1459.000000    50.000000    9453.000000     5.000000  1973.000000
75%    2188.500000    70.000000   11570.000000     6.000000  2001.000000
max    2918.000000   190.000000  215245.000000     9.000000  2010.000000

       YearRemodAdd   BsmtFinSF2  TotalBsmtSF      SalePrice
count   2919.000000  2918.000000  2918.000000    1460.000000
mean    1984.264474    49.582248  1051.777587  180921.195890
std       20.894344   169.205611   440.766258   79442.502883
min     1950.000000     0.000000     0.000000   34900.000000
25%     1965.000000     0.000000   793.000000  129975.000000
50%     1993.000000     0.000000   989.500000  163000.000000
75%     2004.000000     0.000000  1302.000000  214000.000000
max     2010.000000  1526.000000  6110.000000  755000.000000
         Id  MSSubClass  MSZoning  LotArea  LotConfig  BldgType  OverallCond  \
0     False       False     False    False      False     False        False
1     False       False     False    False      False     False        False
2     False       False     False    False      False     False        False
3     False       False     False    False      False     False        False
4     False       False     False    False      False     False        False
...     ...         ...       ...      ...        ...       ...          ...
2914  False       False     False    False      False     False        False
2915  False       False     False    False      False     False        False
2916  False       False     False    False      False     False        False
2917  False       False     False    False      False     False        False
2918  False       False     False    False      False     False        False

      YearBuilt  YearRemodAdd  Exterior1st  BsmtFinSF2  TotalBsmtSF  SalePrice
0         False         False        False       False        False      False
1         False         False        False       False        False      False
2         False         False        False       False        False      False
3         False         False        False       False        False      False
4         False         False        False       False        False      False
...         ...           ...          ...         ...          ...        ...
2914      False         False        False       False        False       True
2915      False         False        False       False        False       True
2916      False         False        False       False        False       True
2917      False         False        False       False        False       True
2918      False         False        False       False        False       True

[2919 rows x 13 columns]

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [5]:
df.drop(columns='Id',axis=1,inplace=True)

In [6]:
df.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [7]:
df['SalePrice']=df['SalePrice'].fillna(
    df['SalePrice'].mean()
)

In [8]:
cols=['MSZoning','LotConfig','BldgType','Exterior1st']
df=pd.get_dummies(df,columns=cols,drop_first=True)

In [9]:
df

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
1,20,9600,8,1976,1976,0.0,1262.0,181500.00000,False,False,...,False,False,False,True,False,False,False,False,False,False
2,60,11250,5,2001,2002,0.0,920.0,223500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
3,70,9550,5,1915,1970,0.0,756.0,140000.00000,False,False,...,False,False,False,False,False,False,False,False,True,False
4,60,14260,5,2000,2000,0.0,1145.0,250000.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,1936,7,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2915,160,1894,5,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2916,20,20000,7,1960,1996,0.0,1224.0,180921.19589,False,False,...,False,False,False,False,False,False,False,True,False,False
2917,85,10441,5,1992,1992,0.0,912.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False
2918,60,9627,5,1993,1994,0.0,996.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum().sort_values(ascending=False)
df=df.dropna()

In [11]:
X=df.drop(columns='SalePrice')
y=df['SalePrice']

In [12]:
X=X.astype(int)

In [13]:
X.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0,856,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,20,9600,8,1976,1976,0,1262,0,0,1,...,0,0,0,1,0,0,0,0,0,0
2,60,11250,5,2001,2002,0,920,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,70,9550,5,1915,1970,0,756,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,60,14260,5,2000,2000,0,1145,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [15]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred=model.predict(X_test)

In [17]:
from sklearn.metrics import root_mean_squared_error,mean_absolute_error,r2_score,mean_absolute_percentage_error,mean_squared_error
import numpy as np
print("R2 Score is",r2_score(y_test,y_pred))
print("MSE is",mean_squared_error(y_test,y_pred))
print("RMSE is",np.sqrt(mean_squared_error(y_test,y_pred)))
print(mean_absolute_percentage_error(y_test,y_pred))

R2 Score is 0.3091193863879039
MSE is 2422884053.4618187
RMSE is 49222.80013836899
0.20603672937866943

In [18]:
X

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0,856,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,20,9600,8,1976,1976,0,1262,0,0,1,...,0,0,0,1,0,0,0,0,0,0
2,60,11250,5,2001,2002,0,920,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,70,9550,5,1915,1970,0,756,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,60,14260,5,2000,2000,0,1145,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,1936,7,1970,1970,0,546,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2915,160,1894,5,1970,1970,0,546,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2916,20,20000,7,1960,1996,0,1224,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2917,85,10441,5,1992,1992,0,912,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2918,60,9627,5,1993,1994,0,996,0,0,1,...,0,1,0,0,0,0,0,0,0,0

In [19]:
num_cols=df.select_dtypes(include=['float64','int64']).columns

for col in num_cols:
    df[col]=df[col].fillna(df[col].median())

C:\Users\HP\AppData\Local\Temp\ipykernel_16840\2796015283.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=df[col].fillna(df[col].median())

In [20]:
cat_cols=df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col]=df[col].fillna(df[col].mode())

In [21]:
df.isna().sum()

MSSubClass             0
LotArea                0
OverallCond            0
YearBuilt              0
YearRemodAdd           0
BsmtFinSF2             0
TotalBsmtSF            0
SalePrice              0
MSZoning_FV            0
MSZoning_RH            0
MSZoning_RL            0
MSZoning_RM            0
LotConfig_CulDSac      0
LotConfig_FR2          0
LotConfig_FR3          0
LotConfig_Inside       0
BldgType_2fmCon        0
BldgType_Duplex        0
BldgType_Twnhs         0
BldgType_TwnhsE        0
Exterior1st_AsphShn    0
Exterior1st_BrkComm    0
Exterior1st_BrkFace    0
Exterior1st_CBlock     0
Exterior1st_CemntBd    0
Exterior1st_HdBoard    0
Exterior1st_ImStucc    0
Exterior1st_MetalSd    0
Exterior1st_Plywood    0
Exterior1st_Stone      0
Exterior1st_Stucco     0
Exterior1st_VinylSd    0
Exterior1st_Wd Sdng    0
Exterior1st_WdShing    0
dtype: int64

In [22]:
X=df.drop(columns=['SalePrice'])
y=df['SalePrice']

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [24]:
y_pred=model.predict(X_test)

In [25]:
print("R2 Score is",r2_score(y_test,y_pred))
print("MSE is",mean_squared_error(y_test,y_pred))
print("RMSE is",np.sqrt(mean_squared_error(y_test,y_pred)))
print(mean_absolute_percentage_error(y_test,y_pred))

R2 Score is 0.3091193863879037
MSE is 2422884053.4618196
RMSE is 49222.800138369006
0.2060367293786694

In [27]:
# 1. load data
df = pd.read_csv("../datasets/HousePricePrediction.csv")

# 2. drop unwanted columns
df.drop(columns='Id', inplace=True)

# 3. handle numerical nulls
num_cols = df.select_dtypes(include=['float64','int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# 4. handle categorical nulls
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# 5. encode ALL categorical columns
df = pd.get_dummies(df, drop_first=True)

# 6. split X and y
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

# 7. train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 8. train model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

# 9. predictions
y_pred = model.predict(X_test)

# 10. evaluation
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

print("R2:", r2_score(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2: 0.3371869620414223
RMSE: 49409.369260568325